services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ${HA_CONFIG_DIR}:/config
      - ${HA_ENTRYPOINT_SCRIPT}:/docker-entrypoint.sh
    environment:
      - TZ=${TZ}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB_HOST}:5432/${POSTGRES_DB_NAME}
    entrypoint: ["/bin/bash", "${HA_ENTRYPOINT_SCRIPT}"]
    networks:
      - homelab_network

networks:
  homelab_network:
    external: true
